---
functional:
  - Любой пользователь должен иметь возможность подключиться к игре без авторизации
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность авторизации любым из предложенных способов (посредством ввода логина и пароля, через GitHub или Discord)
  - Cуществует возможность восстановить данные для входа через опцию "Forgot your password?"
  - Существует возможность создания игр и турниров с различными параметрами
  - Созданная игра/турнир отображается доступной для подключения другим пользователям
  - Пользователь должен иметь возможность подключаться к созданной другим пользователем игре/турниру
  - Каждому игроку отображается код своего соперника в режиме онлайн, время игры и задание
  - Каждый игрок должен иметь кнопку "Check" для проверки своего решения. Количество попыток проверки не должно быть ограничено
  - Если один из игроков выходит из игры, второй игрок должен иметь возможность продолжать играть. Первый игрок должен иметь возможность переподключиться в любой момент до завершения игры
  - Когда один из игроков находит верное решение, обоим игрокам должно отображаться модальное окно, которое сообщает о победителе игры
  - Победивший игрок должен иметь возможность выйти из игры, нажав кнопку "Exit". После выхода, кнопка "Check" должна быть неактивной, однако игрок может просмотреть свой код
  - Проигравший игрок может выбрать выход или продолжить играть до конца
  - Когда оба игрока вышли из игры, она считается полностью завершенной и должна быть удалена из памяти
  - В процессе игры существует возможность сдаться
  - Помимо подключения к игре существует возможность просматривать игры и турниры других игроков
  - В процессе игры существует возможность изменения локализации (языков)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Существует возможность полной локализации сайта на русский язык (а не только внутри батла)
 
