---
functional:
  - Любой пользователь должен иметь возможность подключиться к игре без регистрации
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность авторизации любым из предложенных способов (емейл/пароль, GitHub, Discord)
  - Cуществует возможность восстановить данные для входа через опцию "Forgot your password?"
  - Существует возможность создания игр и турниров
  - В процессе игры отображается задание, свой редактор кода и редактор кода соперника, код соперника в режиме онлайн, таймер игры
  - Существует возможность проверить ответ на верный/неверный
  - Существуют различные исходы игры (победа, проигрыш)
  - Игра должна завершаться при выходе из нее всех игроков
  - В процессе игры существует возможность сдаться
  - Пользователь должен иметь возможность переподключиться к игре
  - Доступны для просмотра списки текущих и завершенных игр и турниров
  - В процессе игры существует возможность изменения локализации (языков)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Существует возможность полной локализации сайта на русский язык (а не только внутри батла)
  - Текст на кнопках и пр. и в других местах сайта должен быть прописан одинаково, в едином формате и регистре. Например, "Sign in" и "Sign up", "CREATE A GAME". На главной странице сайта указано "in" и "up", а при переходе в форму регистрации/авторизации данные элементы имеют вид "In" и "Up",на странице создания игр кнопка создания игры имеет вид "CREATE A GAME", а при создании во всплывающем окне имеет другой вид "Create a game".  
 
